# Generated by Django 4.0.1 on 2022-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
