# Generated by Django 4.0.1 on 2022-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_alter_recharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='prepaid',
            field=models.BooleanField(default=True),
        ),
    ]
