# Generated by Django 4.0.1 on 2022-01-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0003_plan_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recharge.operator'),
        ),
    ]
