# Generated by Django 4.0.1 on 2022-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0004_plan_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='internet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
