# Generated by Django 4.0.1 on 2022-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0005_alter_plan_internet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='internet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
